version: '3'

services:
  frontend:
    build: ./react-frontend
    command: /bin/sh -c "npm install && npm run dev -- --host"
    container_name: react-frontend
    ports:
      - "5173:5173"
    volumes: 
      - ./react-frontend:/home/node/app
    depends_on:
      - backend

  backend:
    build: ./vendas-online-backend
    container_name: backend-nestjs
    ports:
      - "3330:8080"
    environment:
      - DB_HOST=database
    depends_on:
      - database

  database:
    build: ./docker/postgres
    container_name: database
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./docker/dbdata:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=venda
  
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   tty: true
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   ports:
  #     - "8000:80"
  #   depends_on:
  #     - database